# Generated by Django 4.0.7 on 2023-07-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='varsta',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
