# Generated by Django 4.0.7 on 2023-07-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0002_person_varsta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='varsta',
            field=models.IntegerField(default=0),
        ),
    ]
